<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a0f0fe40-a717-473a-9d67-18163a94b224</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
