<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>39d96e22-b1a6-4619-8f2b-e93692ae82d6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of strings ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
