<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Pattern Can Be Found</name>
  <uuid>5f304356-667d-4fbf-a886-a7410dd839c1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	regex pattern "f[ai]b" can be found in 'Sample Text' 
then
	set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
