<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Pattern Found</name>
  <uuid>7a46ddb1-bcba-431a-b06c-ee4afcbc569b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	regex pattern 'Pattern Found Pattern' can be found in 'Pattern Found Sample' 
then
	set decision to true;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
